# defect detect config
detect:
  filePath:
    weights: './weights/steel_detector/bests.pt'
    logs: './arith_logs/detect_logs'
    rois: './result_roi_4k'
    srcs:
      - './data/hengqie'
      -
      -
  
  dbInfo:
    db_ip: '127.0.0.1'
    db_user: 'root'
    db_psd: 'nercar'
    db_name: 'ncdcoldstrip'

  infoParameter:
    img_size: 614
    conf_thres: 0.15
    iou_thres: 0.45
    bin_thres: 0.35
    edge_shift: 0
    max_det: 1000
    pro_num: 3
    # 检测图像存储最大卷数
    max_save_steelno: 2
    # 0表示存储所有图像
    # >0 表示对此取余进行覆盖存储图像
    loop: 600
    # 'cuda device, i.e. 0 or 0,1,2,3 or cpu'
    device: '0'
    cam_res: '4k'
    schema: 1
    half: False
    dnn: False
    debug: False
# defect recognition config
classifier:
  filePath:
    weights: './weights/steel_classifier/steel_model_classifier.h5'
    ini: './weights/steel_classifier/steel_classifier_interaction.ini'
    xml: './weights/steel_classifier/steel_class_table.xml'
    logs: './arith_logs/classifier_logs'
    input: './result_roi_4k'
    # 主要用于分类结果的存储，便于样本的收集
    internal_number: (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45)
    #internal_number: ()
    offline_result: './classification_result'
    # 新平台需要将数据保存的目录,有几个相机就对应有几个
    schema:
      # 有无算法测试程序
      flag: 1
      camera1: 'F:/defectImg1'
      camera2: 'F:/defectImg2'
  dbInfo:
    db_ip: '127.0.0.1'
    db_user: 'root'
    db_psd: 'nercar'
    # 中转站临时库和表
    transfers:
      db_name: 'temp'
      camera1: 'tempcam1'
      camera2: 'tempcam2'
    # 正式表和库
    using:
      db_name: 'ncdcoldstripdefect'
      camera1: 'camdefect1'
      camera2: 'camdefect2'
  infoParameter:
    bs: 64
    # 数据库中为背景的类别ID(字段class:0)
    negative: 0
    # 忽略分数
    score_ignore: 0
    #相机数
    cam_num: 4
    # 0.1.2.3 or cpu
    device: '0'
    dynamicsize: False
    debug: False
    use_classifier: False
# 数据库中信息后处理
dbinfoprocess:
  filePath:
    logs: './arith_logs/data_pprocess_logs'
  dbInfo:
    db_ip: '127.0.0.1'
    db_user: 'root'
    db_psd: 'nercar'
    # 中转站临时库和表
    transfers:
      db_name: 'temp'
      camera1: 'tempcam1'
      camera2: 'tempcam2'
    # 正式表和库
    using:
      db_name: 'ncdcoldstripdefect'
      camera1: 'camdefect1'
      camera2: 'camdefect2'
  infoParameter:
    #相机数
    cam_num: 2